/** Copyright 2026 Google LLC — Apache-2.0 */

/**
 * Source of truth: csp/frontend/src/app/audio/audio.constants.ts
 * and the languages[]/voices[] arrays in audio.component.ts.
 * Copied EXACTLY — do not paraphrase, abbreviate, or invent entries.
 */

export const LANGUAGES: ReadonlyArray<{ code: string; name: string }> = [
  { code: "ar-XA", name: "Arabic" },
  { code: "bg-BG", name: "Bulgarian (Bulgaria)" },
  { code: "bn-IN", name: "Bengali (India)" },
  { code: "cmn-CN", name: "Mandarin Chinese" },
  { code: "cs-CZ", name: "Czech (Czech Republic)" },
  { code: "da-DK", name: "Danish (Denmark)" },
  { code: "de-DE", name: "German (Germany)" },
  { code: "el-GR", name: "Greek (Greece)" },
  { code: "en-AU", name: "English (Australia)" },
  { code: "en-GB", name: "English (UK)" },
  { code: "en-IN", name: "English (India)" },
  { code: "en-US", name: "English (United States)" },
  { code: "es-ES", name: "Spanish (Spain)" },
  { code: "es-US", name: "Spanish (US)" },
  { code: "fi-FI", name: "Finnish (Finland)" },
  { code: "fr-CA", name: "French (Canada)" },
  { code: "fr-FR", name: "French (France)" },
  { code: "gu-IN", name: "Gujarati (India)" },
  { code: "he-IL", name: "Hebrew (Israel)" },
  { code: "hi-IN", name: "Hindi (India)" },
  { code: "hu-HU", name: "Hungarian (Hungary)" },
  { code: "id-ID", name: "Indonesian (Indonesia)" },
  { code: "it-IT", name: "Italian (Italy)" },
  { code: "ja-JP", name: "Japanese (Japan)" },
  { code: "kn-IN", name: "Kannada (India)" },
  { code: "ko-KR", name: "Korean (South Korea)" },
  { code: "lt-LT", name: "Lithuanian (Lithuania)" },
  { code: "lv-LV", name: "Latvian (Latvia)" },
  { code: "ml-IN", name: "Malayalam (India)" },
  { code: "mr-IN", name: "Marathi (India)" },
  { code: "nb-NO", name: "Norwegian (Norway)" },
  { code: "nl-BE", name: "Dutch (Belgium)" },
  { code: "nl-NL", name: "Dutch (Netherlands)" },
  { code: "pl-PL", name: "Polish (Poland)" },
  { code: "pt-BR", name: "Portuguese (Brazil)" },
  { code: "ro-RO", name: "Romanian (Romania)" },
  { code: "ru-RU", name: "Russian (Russia)" },
  { code: "sk-SK", name: "Slovak (Slovakia)" },
  { code: "sr-RS", name: "Serbian (Serbia)" },
  { code: "sv-SE", name: "Swedish (Sweden)" },
  { code: "ta-IN", name: "Tamil (India)" },
  { code: "te-IN", name: "Telugu (India)" },
  { code: "th-TH", name: "Thai (Thailand)" },
  { code: "tr-TR", name: "Turkish (Turkey)" },
  { code: "uk-UA", name: "Ukrainian (Ukraine)" },
  { code: "vi-VN", name: "Vietnamese (Vietnam)" },
];

export const VOICES: ReadonlyArray<{ id: string; name: string }> = [
  { id: "Achernar", name: "Achernar (Female)" },
  { id: "Achird", name: "Achird (Male)" },
  { id: "Algenib", name: "Algenib (Male)" },
  { id: "Algieba", name: "Algieba (Male)" },
  { id: "Alnilam", name: "Alnilam (Male)" },
  { id: "Aoede", name: "Aoede (Female)" },
  { id: "Autonoe", name: "Autonoe (Female)" },
  { id: "Callirrhoe", name: "Callirrhoe (Female)" },
  { id: "Charon", name: "Charon (Male)" },
  { id: "Despina", name: "Despina (Female)" },
  { id: "Enceladus", name: "Enceladus (Male)" },
  { id: "Erinome", name: "Erinome (Female)" },
  { id: "Fenrir", name: "Fenrir (Male)" },
  { id: "Gacrux", name: "Gacrux (Female)" },
  { id: "Iapetus", name: "Iapetus (Male)" },
  { id: "Kore", name: "Kore (Female)" },
  { id: "Laomedeia", name: "Laomedeia (Female)" },
  { id: "Leda", name: "Leda (Female)" },
  { id: "Orus", name: "Orus (Male)" },
  { id: "Puck", name: "Puck (Male)" },
  { id: "Pulcherrima", name: "Pulcherrima (Female)" },
  { id: "Rasalgethi", name: "Rasalgethi (Male)" },
  { id: "Sadachbia", name: "Sadachbia (Male)" },
  { id: "Sadaltager", name: "Sadaltager (Male)" },
  { id: "Schedar", name: "Schedar (Male)" },
  { id: "Sulafat", name: "Sulafat (Female)" },
  { id: "Umbriel", name: "Umbriel (Male)" },
  { id: "Vindemiatrix", name: "Vindemiatrix (Female)" },
  { id: "Zephyr", name: "Zephyr (Female)" },
  { id: "Zubenelgenubi", name: "Zubenelgenubi (Male)" },
];

export const DEFAULT_LANGUAGE = "en-US";
export const DEFAULT_VOICE = "Puck";
